### PR TITLE
Bring in Missing <time.h> Header

### LINKED ISSUE #322: slight build problem in FreeBSD-12.1, with clang-8.0.1
```
In file included from /home/edscott/GIT/OPM/opm-upscaling/opm/upscaling/writeECLData.cpp:25:
/home/edscott/GIT/OPM/opm-upscaling/opm/upscaling/writeECLData.hpp:37:21: error: unknown type name
      'time_t'
                    time_t current_posix_time,
                    ^
1 error generated.
```

---

Fixed by adding a simple:
```C++
#include <time.h>
```

### PR DESCRIPTION
**Pull request by bska**
Needed to bring a declaration of 'time_t' into scope.

Submitted by: Edscott Wilson Garcia

Fixes #322

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Self-merging as trivial and fixes a build issue.

File: opm/upscaling/writeECLData.hpp [hunk 1]
```diff
@@ -23,6 +23,8 @@
 
 #include <string>
 
+#include <time.h>
```
Comment (blattms) [inline opm/upscaling/writeECLData.hpp:26]: Shouldn't this have been `#include ctime` as we are using C++?

Comment (bska) [reply opm/upscaling/writeECLData.hpp:26]: > Shouldn't this have been `#include ctime` as we are using C++?

Actually, no.  The function signature uses `time_t`, not `std::time_t`.  We could **arguably** write this as
```C++
#include <ctime>

using std::time_t;
```
but we get that for free by using the C header instead.

Comment (bska) [reply opm/upscaling/writeECLData.hpp:26]: That said, I suppose we could update the signature to `std::time_t`, but i didn't want to track down all callers and fix those too.
